/// Flutter icons ElapseIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ElapseIcons
///      fonts:
///       - asset: fonts/ElapseIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ElapseIcons {
  ElapseIcons._();

  static const _kFontFam = 'ElapseIcons';
  static const _kFontPkg = null;

  static const IconData home = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData teams = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tournaments = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData matches = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
